server:
  port: 8081
  servlet:
    context-path: /api/v1

spring:
  application:
    name: book-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      maximumPoolSize: 5
      poolName: bs-pool
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
  kafka:
    bootstrap-servers: ${BROKER_SERVER}
    consumer:
      group-id: "book-service"
      client-id: "booking-consumer"
    producer:
      client-id: "booking-status-producer"
    producer-topic-name: "booking-status"
    consumer-topic-name: "booking-library-book"

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS}