api:
  url:
    books: http://localhost:9000/api/v1/books
    booking: http://localhost:9000/api/v1/bookings

logging:
  level:
    andrey.library.client.feign.BookClient: DEBUG
  file:
    name: logs/client.log
